-- MySQL Script generated by MySQL Workbench
-- 09/20/15 21:56:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shopping_cart
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shopping_cart
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shopping_cart` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `shopping_cart` ;

-- -----------------------------------------------------
-- Table `shopping_cart`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_cart`.`user_roles` (
  `id` INT PRIMARY KEY AUTO_INCREMENT COMMENT '',
  `role_name` VARCHAR(45) NOT NULL COMMENT '',
  `can_sell_products` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `can_buy_products` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `can_add_categories` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `can_delete_categories` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `can_add_product` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `can_delete_product` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `can_move_products_btw_categories` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `can_edit_quantities` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `can_reorder_products` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `I_am_admin` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  UNIQUE INDEX `role_name_UNIQUE` (`role_name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_cart`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_cart`.`users` (
  `id` INT PRIMARY KEY AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `first_name` VARCHAR(45) NULL COMMENT '',
  `last_name` VARCHAR(45) NOT NULL COMMENT '',
  `age` INT NULL COMMENT '',
  `gender` CHAR(1) NOT NULL DEFAULT 'u' COMMENT '',
  `join_date` DATETIME NOT NULL COMMENT '',
  `balance` DECIMAL(10,2) ZEROFILL NULL DEFAULT 5000.00 COMMENT '',
  `intrested_in_buying` VARCHAR(245) NULL COMMENT '',
  `selling` VARCHAR(245) NULL COMMENT '',
  `about_my_business` VARCHAR(245) NULL COMMENT '',
  `user_role_id` INT NOT NULL COMMENT '',
  UNIQUE INDEX `username_UNIQUE` (`username` ASC)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '',
  INDEX `fk_users_user_roles_idx` (`user_role_id` ASC)  COMMENT '',
  CONSTRAINT `fk_users_user_roles`
    FOREIGN KEY (`user_role_id`)
    REFERENCES `shopping_cart`.`user_roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_cart`.`chart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_cart`.`chart` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `user_id`)  COMMENT '',
  INDEX `fk_chart_users1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_chart_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `shopping_cart`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_cart`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_cart`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `product_name` VARCHAR(100) NOT NULL COMMENT '',
  `price` DECIMAL(10,2) NOT NULL COMMENT '',
  `amount` INT NOT NULL COMMENT '',
  `description` VARCHAR(245) NULL COMMENT '',
  `posted_on` DATETIME NULL COMMENT '',
  `seller_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `seller_id`)  COMMENT '',
  INDEX `fk_products_users1_idx` (`seller_id` ASC)  COMMENT '',
  CONSTRAINT `fk_products_users1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `shopping_cart`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_cart`.`chart_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_cart`.`chart_has_products` (
  `chart_id` INT NOT NULL COMMENT '',
  `product_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`chart_id`, `product_id`)  COMMENT '',
  INDEX `fk_chart_has_products_products1_idx` (`product_id` ASC)  COMMENT '',
  INDEX `fk_chart_has_products_chart1_idx` (`chart_id` ASC)  COMMENT '',
  CONSTRAINT `fk_chart_has_products_chart1`
    FOREIGN KEY (`chart_id`)
    REFERENCES `shopping_cart`.`chart` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chart_has_products_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `shopping_cart`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_cart`.`product_reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_cart`.`product_reviews` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  `product_id` INT NOT NULL COMMENT '',
  `posted_on` DATETIME NOT NULL COMMENT '',
  `comment` VARCHAR(245) NOT NULL COMMENT '',
  `stars_given` INT NULL COMMENT '',
  PRIMARY KEY (`id`, `user_id`)  COMMENT '',
  INDEX `fk_comments_users1_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_comments_products1_idx` (`product_id` ASC)  COMMENT '',
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `shopping_cart`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `shopping_cart`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_cart`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_cart`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `image_type` VARCHAR(25) NOT NULL DEFAULT '' COMMENT '',
  `image` BLOB NOT NULL COMMENT '',
  `image_size` VARCHAR(25) NOT NULL DEFAULT '' COMMENT '',
  `image_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '',
  `product_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `product_id`)  COMMENT '',
  INDEX `fk_images_products1_idx` (`product_id` ASC)  COMMENT '',
  CONSTRAINT `fk_images_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `shopping_cart`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_cart`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_cart`.`categories` (
  `id` INT PRIMARY KEY AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_cart`.`categories_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_cart`.`categories_has_products` (
  `category_id` INT NOT NULL COMMENT '',
  `product_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`category_id`, `product_id`)  COMMENT '',
  INDEX `fk_categories_has_products_products1_idx` (`product_id` ASC)  COMMENT '',
  INDEX `fk_categories_has_products_categories1_idx` (`category_id` ASC)  COMMENT '',
  CONSTRAINT `fk_categories_has_products_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `shopping_cart`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categories_has_products_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `shopping_cart`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_cart`.`promotion_criteria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_cart`.`promotion_criteria` (
  `id` INT PRIMARY KEY AUTO_INCREMENT COMMENT '',
  `user_days_active` INT NULL DEFAULT 0 COMMENT '',
  `user_activity` DECIMAL(10,0) NULL DEFAULT 0 COMMENT '',
  `user_min_cash` DECIMAL(10,2) NULL COMMENT '',
  `criterion_name` VARCHAR(85) NOT NULL COMMENT '',
  `no_criterion` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_cart`.`promotions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_cart`.`promotions` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `discount` DECIMAL(10,0) NOT NULL COMMENT '',
  `start_date` DATETIME NOT NULL COMMENT '',
  `end_date` DATETIME NOT NULL COMMENT '',
  `promotion_criterion_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `promotion_criterion_id`)  COMMENT '',
  INDEX `fk_promotions_promotion_criteria1_idx` (`promotion_criterion_id` ASC)  COMMENT '',
  CONSTRAINT `fk_promotions_promotion_criteria1`
    FOREIGN KEY (`promotion_criterion_id`)
    REFERENCES `shopping_cart`.`promotion_criteria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_cart`.`products_has_promotions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_cart`.`products_has_promotions` (
  `product_id` INT NOT NULL COMMENT '',
  `promotion_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`product_id`, `promotion_id`)  COMMENT '',
  INDEX `fk_products_has_promotions_promotions1_idx` (`promotion_id` ASC)  COMMENT '',
  INDEX `fk_products_has_promotions_products1_idx` (`product_id` ASC)  COMMENT '',
  CONSTRAINT `fk_products_has_promotions_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `shopping_cart`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_promotions_promotions1`
    FOREIGN KEY (`promotion_id`)
    REFERENCES `shopping_cart`.`promotions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_cart`.`promotions_has_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_cart`.`promotions_has_categories` (
  `promotion_id` INT NOT NULL COMMENT '',
  `category_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`promotion_id`, `category_id`)  COMMENT '',
  INDEX `fk_promotions_has_categories_categories1_idx` (`category_id` ASC)  COMMENT '',
  INDEX `fk_promotions_has_categories_promotions1_idx` (`promotion_id` ASC)  COMMENT '',
  CONSTRAINT `fk_promotions_has_categories_promotions1`
    FOREIGN KEY (`promotion_id`)
    REFERENCES `shopping_cart`.`promotions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_promotions_has_categories_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `shopping_cart`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
